// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MasoudHeydari/Exercise_1/Task2_imagy/ent/image"
	"github.com/MasoudHeydari/Exercise_1/Task2_imagy/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iu *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetOriginalURL sets the "original_url" field.
func (iu *ImageUpdate) SetOriginalURL(s string) *ImageUpdate {
	iu.mutation.SetOriginalURL(s)
	return iu
}

// SetLocalName sets the "local_name" field.
func (iu *ImageUpdate) SetLocalName(s string) *ImageUpdate {
	iu.mutation.SetLocalName(s)
	return iu
}

// SetFileExtension sets the "file_extension" field.
func (iu *ImageUpdate) SetFileExtension(s string) *ImageUpdate {
	iu.mutation.SetFileExtension(s)
	return iu
}

// SetFileSize sets the "file_size" field.
func (iu *ImageUpdate) SetFileSize(i int64) *ImageUpdate {
	iu.mutation.ResetFileSize()
	iu.mutation.SetFileSize(i)
	return iu
}

// AddFileSize adds i to the "file_size" field.
func (iu *ImageUpdate) AddFileSize(i int64) *ImageUpdate {
	iu.mutation.AddFileSize(i)
	return iu
}

// SetDownloadDate sets the "download_date" field.
func (iu *ImageUpdate) SetDownloadDate(t time.Time) *ImageUpdate {
	iu.mutation.SetDownloadDate(t)
	return iu
}

// SetNillableDownloadDate sets the "download_date" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableDownloadDate(t *time.Time) *ImageUpdate {
	if t != nil {
		iu.SetDownloadDate(*t)
	}
	return iu
}

// Mutation returns the ImageMutation object of the builder.
func (iu *ImageUpdate) Mutation() *ImageMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ImageUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ImageUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *ImageUpdate) check() error {
	if v, ok := iu.mutation.OriginalURL(); ok {
		if err := image.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "Image.original_url": %w`, err)}
		}
	}
	if v, ok := iu.mutation.LocalName(); ok {
		if err := image.LocalNameValidator(v); err != nil {
			return &ValidationError{Name: "local_name", err: fmt.Errorf(`ent: validator failed for field "Image.local_name": %w`, err)}
		}
	}
	if v, ok := iu.mutation.FileExtension(); ok {
		if err := image.FileExtensionValidator(v); err != nil {
			return &ValidationError{Name: "file_extension", err: fmt.Errorf(`ent: validator failed for field "Image.file_extension": %w`, err)}
		}
	}
	return nil
}

func (iu *ImageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.OriginalURL(); ok {
		_spec.SetField(image.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := iu.mutation.LocalName(); ok {
		_spec.SetField(image.FieldLocalName, field.TypeString, value)
	}
	if value, ok := iu.mutation.FileExtension(); ok {
		_spec.SetField(image.FieldFileExtension, field.TypeString, value)
	}
	if value, ok := iu.mutation.FileSize(); ok {
		_spec.SetField(image.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := iu.mutation.AddedFileSize(); ok {
		_spec.AddField(image.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := iu.mutation.DownloadDate(); ok {
		_spec.SetField(image.FieldDownloadDate, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetOriginalURL sets the "original_url" field.
func (iuo *ImageUpdateOne) SetOriginalURL(s string) *ImageUpdateOne {
	iuo.mutation.SetOriginalURL(s)
	return iuo
}

// SetLocalName sets the "local_name" field.
func (iuo *ImageUpdateOne) SetLocalName(s string) *ImageUpdateOne {
	iuo.mutation.SetLocalName(s)
	return iuo
}

// SetFileExtension sets the "file_extension" field.
func (iuo *ImageUpdateOne) SetFileExtension(s string) *ImageUpdateOne {
	iuo.mutation.SetFileExtension(s)
	return iuo
}

// SetFileSize sets the "file_size" field.
func (iuo *ImageUpdateOne) SetFileSize(i int64) *ImageUpdateOne {
	iuo.mutation.ResetFileSize()
	iuo.mutation.SetFileSize(i)
	return iuo
}

// AddFileSize adds i to the "file_size" field.
func (iuo *ImageUpdateOne) AddFileSize(i int64) *ImageUpdateOne {
	iuo.mutation.AddFileSize(i)
	return iuo
}

// SetDownloadDate sets the "download_date" field.
func (iuo *ImageUpdateOne) SetDownloadDate(t time.Time) *ImageUpdateOne {
	iuo.mutation.SetDownloadDate(t)
	return iuo
}

// SetNillableDownloadDate sets the "download_date" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableDownloadDate(t *time.Time) *ImageUpdateOne {
	if t != nil {
		iuo.SetDownloadDate(*t)
	}
	return iuo
}

// Mutation returns the ImageMutation object of the builder.
func (iuo *ImageUpdateOne) Mutation() *ImageMutation {
	return iuo.mutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iuo *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Image entity.
func (iuo *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *ImageUpdateOne) check() error {
	if v, ok := iuo.mutation.OriginalURL(); ok {
		if err := image.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "Image.original_url": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.LocalName(); ok {
		if err := image.LocalNameValidator(v); err != nil {
			return &ValidationError{Name: "local_name", err: fmt.Errorf(`ent: validator failed for field "Image.local_name": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.FileExtension(); ok {
		if err := image.FileExtensionValidator(v); err != nil {
			return &ValidationError{Name: "file_extension", err: fmt.Errorf(`ent: validator failed for field "Image.file_extension": %w`, err)}
		}
	}
	return nil
}

func (iuo *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.OriginalURL(); ok {
		_spec.SetField(image.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := iuo.mutation.LocalName(); ok {
		_spec.SetField(image.FieldLocalName, field.TypeString, value)
	}
	if value, ok := iuo.mutation.FileExtension(); ok {
		_spec.SetField(image.FieldFileExtension, field.TypeString, value)
	}
	if value, ok := iuo.mutation.FileSize(); ok {
		_spec.SetField(image.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := iuo.mutation.AddedFileSize(); ok {
		_spec.AddField(image.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := iuo.mutation.DownloadDate(); ok {
		_spec.SetField(image.FieldDownloadDate, field.TypeTime, value)
	}
	_node = &Image{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
