// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/MasoudHeydari/Exercise_1/Task2_imagy/ent/image"
	"github.com/MasoudHeydari/Exercise_1/Task2_imagy/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescOriginalURL is the schema descriptor for original_url field.
	imageDescOriginalURL := imageFields[1].Descriptor()
	// image.OriginalURLValidator is a validator for the "original_url" field. It is called by the builders before save.
	image.OriginalURLValidator = imageDescOriginalURL.Validators[0].(func(string) error)
	// imageDescLocalName is the schema descriptor for local_name field.
	imageDescLocalName := imageFields[2].Descriptor()
	// image.LocalNameValidator is a validator for the "local_name" field. It is called by the builders before save.
	image.LocalNameValidator = imageDescLocalName.Validators[0].(func(string) error)
	// imageDescFileExtension is the schema descriptor for file_extension field.
	imageDescFileExtension := imageFields[3].Descriptor()
	// image.FileExtensionValidator is a validator for the "file_extension" field. It is called by the builders before save.
	image.FileExtensionValidator = imageDescFileExtension.Validators[0].(func(string) error)
	// imageDescDownloadDate is the schema descriptor for download_date field.
	imageDescDownloadDate := imageFields[5].Descriptor()
	// image.DefaultDownloadDate holds the default value on creation for the download_date field.
	image.DefaultDownloadDate = imageDescDownloadDate.Default.(func() time.Time)
}
