version: "3.9"

services:
  postgres:
    image: postgres:15.0-alpine
    env_file:
      - adapter/store/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - ./adapter/store/postgres/volume:/var/lib/postgresql/data